### ISSUE TITLE
Loud thought

### ISSUE THREAD

**Issue by JikkuJose** [peter-murach/verse#1]
Nice work, but I am not sure about the interface. I think an interface like the following may be better?

``` ruby
require 'verse'

string = Verse::String.new "Some Poetry" +
  "With many lines," +
  "Though with less meaning," +
  "And context"

# and use:

string.align(40, :right)
string.truncate(22, trailing: '... (see more)')
string.wrap(8)
```

**Comment by peter-murach** [comment]
Hi Jikku,

Thank you for taking time to look at the library - I like when people question my code structure!

The way the library is currently implemented is a direct result of my experience using it as one of the dependencies for [tty-table](https://github.com/peter-murach/tty-table). I want the components to be reusable pieces with well focused api surface. For instance, the `Verse::Wrap` has single responsibility, namely, to wrap text and what follows can be easily chained with other text transformations:
```ruby
aligned = Verse.align("some text", 40, :right)
truncated = Verse.truncate(aligned, 22, trailing: '... (see more)')
wrapped = Verse.wrap(truncated, 8)

Verse.wrap(Verse.align(truncated, 30, :center), 10) 
```
There is no mutable state involved, which is important benefit! More importantly, your suggestion would create a very bloated interface going forward, the `Verse::String` would become a god object attracting multitude of responsibilities.

**Comment by JikkuJose** [comment]
Thanks for the pointers! Had recently heard about the benefits of avoiding mutable states, but not sure I understand enough to implement it myself.

Sorry, for making silly arguments to such good API design, may be my inexperience made me say that. Best wishes.

**Comment by peter-murach** [comment]
No worries, feel free to express your opinions, that's why I do open source to share and discuss with people! I find that writing api is a mixture of science and art, things can be argued both ways, I certainly find myself gravitating towards the code that pleases my aesthetics but not necessarily someone else. Yeah sure send me a link and I see whether I can be of any help.

**Comment by JikkuJose** [comment]
Cool, thanks! Though I think its silly to pollute the issue's page with the discussion; In the exercise [Bob](http://exercism.io/submissions/736312a54538483ea43cefdb07592e8d) in exercism.

I tend to feel I have eliminated state as I am not passing anything, but I am not sure. Can you take a look.
